$( function() {
    var availableTags = [
      "GNOCCHI SPECK NOCI E TOMA",
      "FUSILLI AL BAFFO CON GUANCIALE",
      "ZUPPA DI PESCE",
      "LASAGNA CON NOCI, PRIMOSALE E ZUCCHINE",
      "FUSILLI AL PESTO DI ZUCCHINE CON SALMONE",
      "MEZZE PENNE AI CARCIOFI",
      "TROFIE AL FORNO CON SALSICCIA, BESCIAMELLA E PROVOLA",
      "SPAGHETTONI ALLA CREMA DI RICOTTA E ZAFFERANO CON GUANCIALE",
      "PENNE ALL' ARRABBIATA CON FUNGHI",
      "PASTA ALLA CREMA DI PATATE E PECORINO CON POLPO",
      "ZUPPA CREMOSA DI CECI",
      "RISOTTO ZUCCHINE E STRACCHINO",
      "MELANZANE IN CARROZZA",
      "ALETTE DI POLLO ALLA BIRRA",
      "FILETTO DI MERLUZZO IN PADELLA",
      "PESCE SPADA AI SAPORI MEDITERRANEI",
      "PESCE SPADA ALLA BAGNARESE",
      "POLPETTE AL SUGO DI PEPERONI",
      "POLPETTE DI CARCIOFI CON CUORE FILANTE",
      "POLPETTE  TONNO E PATATE",
      "SPEZZATINO ALLA BORGOGNONA",
      "UOVA ALLA CONTADINA",
      "INVOLTINI DI MELANZANE E PESCE SPADA",
      "INVOLTINI PRIMAVERA",
      "PANETTONE SALATO",
      "GIRELLE SFOGLIA SALATE",
      "ROTOLO DI ZUCCHINE CON STRACCHINO E PROSCIUTTO COTTO",
      "INVOLTINI RIPIENI DI SALSICCIA E PROVOLONE",
      "BAILEYS CHOCOLATE POKE CAKE",
      "CIOCCOLATA CALDA BIANCA",
      "CREMA FREDDA AL CAFFÈ",
      "CROSTATA DI FRUTTA",
      "DOLCETTI CON RISO SOFFIATO",
      "GOCCIOLAMISÙ",
      "PASTIERA",
      "PISTACCHIOMISÙ CON NUTELLA",
      "TORTA CUORE DI MAMMA",
      "TORTA FREDDA ROCHER"
    ];
    $( "#tags" ).autocomplete({
      source: availableTags
                                
    });
  } );